# Defining nginx image to be used
FROM nginx AS proxy
# Copying compiled code and nginx config to different folder

WORKDIR /tmp

RUN ls -al
#COPY ../nginx/ usr/share/nginx/html  
RUN ls
COPY  docker/nginx/nginx.conf  /etc/nginx/conf.d/default.conf
RUN mkdir -p /usr/share/nginx/html/home
RUN ls
COPY  tbdfrontend/dist usr/share/nginx/html/home
# Exposing a port, here it means that inside the container 
# the app will be using Port 80 while running
EXPOSE 80
